version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "America/Chicago"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "America/Chicago"
